### ISSUE TITLE
Bug: Error committing to github.

### ISSUE THREAD

**Issue by ptoner** [LargeNFT/large-nft#7]
When commiting Alice to GitHub to test I get the following error.

main.admin.js:7866 TypeError: Cannot read properties of null (reading 'commit')
    at GithubService.commit (main.admin.js:14812:78)
    at async formSubmit (main.admin.js:7858:21)

It maps to the following line in the GitHub service. It seems like "createCommitOnBranch" is null.

latestCommit = createCommitResult.data.data.createCommitOnBranch.commit.commitUrl.split("/").pop();

Investigating and working on a fix.

**Comment by ptoner** [comment]
This seems to happen when the commit fails but it's unclear why it's failing. I *think* it's a timing issue where github is running an action and it messes with the commit history somehow.

**Comment by ptoner** [comment]
In my experience trying it again a little later has worked. Worst case you can delete the repo and the underlying commit problem will go away.

But I'm going to debug it and see if I can figure it out.
